SELECT NAME||'('||SUBSTR(OCCUPATION,1,1)||')' FROM OCCUPATIONS ORDER BY NAME;
SELECT 'There are a total of '||count(*)||' '||LOWER(OCCUPATION)||'s.' FROM OCCUPATIONS GROUP BY OCCUPATION ORDER BY count(*), occupation;
